
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import Models.DatabaseConnection;
import java.net.URL;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Vector;
import javax.swing.ImageIcon;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Illyas
 */
public class SalesItemsAdd extends javax.swing.JFrame {

    /**
     * Creates new form SalesItemsAdd
     */
    public SalesItemsAdd() {
        initComponents();
        URL iconURL = getClass().getResource("Images/AUXANO ICON 20.png");
        ImageIcon icon = new ImageIcon(iconURL);
        this.setIconImage(icon.getImage());
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        getItems();
        lblQuant0.setVisible(false);
        lblQuant.setVisible(false);

    }

    DatabaseConnection dbConnect = new DatabaseConnection();

    public void getItems() {

        try {
            Connection con = dbConnect.getConnection();
            String query = "select distinct(p.prodName) from products_tab p, stocks_tab s where p.prodName = s.prodName and quantity > 0";
            ResultSet rs;
            PreparedStatement pst = con.prepareStatement(query);
            rs = pst.executeQuery();
            txtItemName.removeAllItems();
            txtItemName.addItem("");

            while (rs.next()) {
                txtItemName.addItem(rs.getString("prodName"));

            }
            con.close();
            rs.close();
            pst.close();

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }

    }

    public boolean checkIf(String baString) {

        int count = Sales.tblCreateSO.getModel().getRowCount();
        boolean chk = false;

        if (count != 0) {
            for (int i = 0; i < count; i++) {
                String name = Sales.tblCreateSO.getModel().getValueAt(i, 2).toString();
                if (name.equals(baString)) {
                    chk = true;
                }
            }
        }
        return chk;

    }

    public void getBatchNo(String item) {

        try {
            Connection con = dbConnect.getConnection();

            String query = "select batchNo from stocks_tab where prodName =? and quantity > 0 ORDER BY quantity DESC;";
            PreparedStatement pst = con.prepareStatement(query);
            pst.setString(1, item);
            ResultSet rs = pst.executeQuery();
            txtBatchNo.removeAllItems();

            while (rs.next()) {

                if (!checkIf(rs.getString("batchNo"))) {
                    txtBatchNo.addItem(rs.getString("batchNo"));
                }

            }
            pst.close();
            rs.close();
            con.close();

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }

    }

    public String getQuantity(String batchNo) {

        String quant = "";

        try {
            Connection con = dbConnect.getConnection();
            String query = "select quantity from stocks_tab where batchNo =? ";
            PreparedStatement pst = con.prepareStatement(query);
            pst.setString(1, (String) txtBatchNo.getSelectedItem());
            ResultSet rs = pst.executeQuery();
            if (rs.next()) {
                quant = rs.getString("quantity");
            }
            pst.close();
            rs.close();
            con.close();

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "quant meesd up");
        }

        return quant;
    }

    public boolean getValidation(String itmNam, String batchNo) {
        boolean ret = false;

        DefaultTableModel model = (DefaultTableModel) Sales.tblCreateSO.getModel();
        for (int i = 0; i < Sales.tblCreateSO.getRowCount(); i++) {
            String itnam = Sales.tblCreateSO.getModel().getValueAt(i, 1).toString();
            String bthNo = Sales.tblCreateSO.getModel().getValueAt(i, 2).toString();

            if ((itnam.equals(itmNam)) && (bthNo.equals(batchNo))) {
                ret = true;
            }

        }
        return ret;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnSave = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        txtQuantity = new javax.swing.JTextField();
        btnCancek = new javax.swing.JButton();
        txtItemName = new javax.swing.JComboBox<>();
        cmbRateSel = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        lblErrBatNo = new javax.swing.JLabel();
        lblErrQuantity = new javax.swing.JLabel();
        lblErrItem = new javax.swing.JLabel();
        txtBatchNo = new javax.swing.JComboBox<>();
        lblQuant0 = new javax.swing.JLabel();
        lblQuant = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle(" Auxano PVT LTD.");
        setResizable(false);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("ADD ITEM"));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(136, 36, -1, -1));

        jLabel2.setText("BATCH NO:");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 180, -1, -1));

        jLabel3.setText("ITEM NAME:");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, -1, -1));

        btnSave.setText("SAVE");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        btnSave.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnSaveKeyPressed(evt);
            }
        });
        jPanel3.add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 330, 82, -1));

        jLabel9.setText("QUANTITY:");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 230, -1, -1));
        jPanel3.add(txtQuantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 220, 202, -1));

        btnCancek.setText("CANCEL");
        btnCancek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancekActionPerformed(evt);
            }
        });
        jPanel3.add(btnCancek, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 330, 82, -1));

        txtItemName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtItemNameActionPerformed(evt);
            }
        });
        jPanel3.add(txtItemName, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 120, 202, -1));

        cmbRateSel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MRP", "WSP" }));
        jPanel3.add(cmbRateSel, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 120, 71, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/AUXANO-Logo2.png"))); // NOI18N
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 24, 104, 48));
        jPanel3.add(lblErrBatNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 202, -1, -1));
        jPanel3.add(lblErrQuantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 254, -1, -1));
        jPanel3.add(lblErrItem, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 147, -1, -1));

        txtBatchNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBatchNoActionPerformed(evt);
            }
        });
        jPanel3.add(txtBatchNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 170, 202, -1));

        lblQuant0.setText("Units Available:");
        jPanel3.add(lblQuant0, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 166, -1, 30));

        lblQuant.setText("jLabel6");
        jPanel3.add(lblQuant, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 166, -1, 30));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 691, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 473, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(8, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 10, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnSaveKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSaveKeyPressed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed

        DefaultTableModel model = (DefaultTableModel) Sales.tblCreateSO.getModel();

        String batchNo = txtBatchNo.getSelectedItem().toString();
        String rateSel = cmbRateSel.getSelectedItem().toString();
        String quantity = txtQuantity.getText();
        String quant = lblQuant.getText().toString();

        int pid = 0;
        int realpid = 0;

        double price = 0;
        int subT = 0;
        int quan = 0;
        int quantchk = 0;
        boolean qVal = false;
        boolean bVal = false;

        try {
            quan = Integer.parseInt(quantity);
            quantchk = Integer.parseInt(quant);
            if ((quan > 0)) {
                qVal = true;
                lblErrQuantity.setText("");
            }
        } catch (NumberFormatException e) {
            lblErrQuantity.setText("*invalid");
        }

        if (txtBatchNo.getSelectedItem() == null) {
            lblErrBatNo.setText("*No Stock Available");
        } else {
            bVal = true;
            lblErrBatNo.setText("");
        }

        if (txtItemName.getSelectedIndex() == -1) {
            lblErrItem.setText("*invalid");
        } else {
            lblErrItem.setText("");
        }

        if (txtBatchNo.getSelectedIndex() == -1) {
            lblErrBatNo.setText("*invalid");
        } else {
            lblErrBatNo.setText("");
        }

        if (rateSel.equals("MRP")) {
            try {
                try (Connection con = dbConnect.getConnection()) {
                    String query = "select mrp, prodID from products_tab where prodName =? ";
                    PreparedStatement pst = con.prepareStatement(query);
                    pst.setString(1, txtItemName.getSelectedItem().toString());
                    ResultSet rs = pst.executeQuery();
                    if (rs.next()) {
                        pid = rs.getInt("mrp");
                        realpid = rs.getInt("prodID");
                    }
                    pst.close();
                    rs.close();
                }
            } catch (SQLException e) {
            }
        } else {

            try {
                Connection con = dbConnect.getConnection();

                String query = "select wsp, prodID from products_tab where prodName =? ";
                PreparedStatement pst = con.prepareStatement(query);
                pst.setString(1, txtItemName.getSelectedItem().toString());
                ResultSet rs = pst.executeQuery();
                if (rs.next()) {
                    pid = rs.getInt("wsp");
                    realpid = rs.getInt("prodID");
                }
            } catch (SQLException e) {
            }

        }
        if (qVal == true && bVal == true) {
            subT = pid * quan;   //quantity
        }

        if ((!txtBatchNo.getSelectedItem().equals("")) && !(txtItemName.getSelectedIndex() == -1) && !(txtQuantity.getText().equals(""))) {

            if ((getValidation(txtItemName.getSelectedItem().toString(), txtBatchNo.getSelectedItem().toString()))) {
                JOptionPane.showMessageDialog(null, "Select Different BatchNo!");
            } else if (qVal == true && bVal == true) {

                if ((quan > quantchk)) {
                    JOptionPane.showMessageDialog(null, "Quantity exceeding stock availability!");
                } else {
                    model.addRow(new Object[]{realpid, txtItemName.getSelectedItem().toString(), txtBatchNo.getSelectedItem(), txtQuantity.getText(),
                        pid, subT});

                    dispose();
                }
            } else {
                JOptionPane.showMessageDialog(rootPane, "Enter Correct Values!");
            }

        } else {

            JOptionPane.showMessageDialog(rootPane, "Fill in the blanks");
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnCancekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancekActionPerformed
        // TODO add your handling code here:
        this.dispose();

    }//GEN-LAST:event_btnCancekActionPerformed

    private void txtBatchNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBatchNoActionPerformed
        // TODO add your handling code here:

        lblQuant.setText(getQuantity((String) txtBatchNo.getSelectedItem()));
        lblQuant0.setVisible(true);
        lblQuant.setVisible(true);

    }//GEN-LAST:event_txtBatchNoActionPerformed

    private void txtItemNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtItemNameActionPerformed
        // TODO add your handling code here:
        if (txtItemName.getSelectedIndex() == -1) {
            txtBatchNo.removeAllItems();
        } else {
            getBatchNo((String) txtItemName.getSelectedItem());
        }
    }//GEN-LAST:event_txtItemNameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SalesItemsAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SalesItemsAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SalesItemsAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SalesItemsAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new SalesItemsAdd().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancek;
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox<String> cmbRateSel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblErrBatNo;
    private javax.swing.JLabel lblErrItem;
    private javax.swing.JLabel lblErrQuantity;
    private javax.swing.JLabel lblQuant;
    private javax.swing.JLabel lblQuant0;
    public javax.swing.JComboBox<String> txtBatchNo;
    public javax.swing.JComboBox<String> txtItemName;
    public javax.swing.JTextField txtQuantity;
    // End of variables declaration//GEN-END:variables
}
